# Generated by Django 2.1 on 2018-10-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_auto_20181023_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='Imagem'),
        ),
    ]
