# Generated by Django 2.1 on 2018-10-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0005_auto_20181023_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='pic_folder/', verbose_name='Imagem'),
        ),
    ]
